apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: 2018-11-28T15:30:12Z
  generation: 5
  labels:
    app: guardedbox
  name: guardedbox
  namespace: default
  resourceVersion: "104819"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/guardedbox
  uid: 7f1719a3-f322-11e8-868f-42010a84013b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guardedbox
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: guardedbox
    spec:
      containers:
      - args:
        - --spring.config.location=file:/etc/config/guardedbox-config.properties,file:/etc/secrets/guardedbox-secrets.properties
        image: s3curitybug/guardedbox
        imagePullPolicy: Always
        name: guardedbox
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
        - mountPath: /etc/secrets
          name: secrets-volume
          readOnly: true
        - mountPath: /etc/cert
          name: cert-volume
          readOnly: true
      - command:
        - /cloud_sql_proxy
        - -instances=s3curitybug-guardedbox:europe-west1:guardedbox-mysql=tcp:3306
        - -credential_file=/secrets/cloudsql/credentials.json
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        imagePullPolicy: IfNotPresent
        name: cloudsql-proxy
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /secrets/cloudsql
          name: cloudsql-instance-credentials
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: guardedbox-config
        name: config-volume
      - name: secrets-volume
        secret:
          defaultMode: 420
          secretName: guardedbox-secret
      - name: cloudsql-instance-credentials
        secret:
          defaultMode: 420
          secretName: cloudsql-instance-credentials
      - name: cert-volume
        secret:
          defaultMode: 420
          secretName: guardedbox-cert
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-11-28T15:32:13Z
    lastUpdateTime: 2018-11-28T15:32:13Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
