apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-11-28T22:43:49Z
  labels:
    app: guardedbox
  name: guardedbox-service
  namespace: default
  resourceVersion: "185862"
  selfLink: /api/v1/namespaces/default/services/guardedbox-service
  uid: 12d98c53-f35f-11e8-868f-42010a84013b
spec:
  clusterIP: 10.19.244.249
  externalTrafficPolicy: Cluster
  ports:
  - name: guardedbox
    nodePort: 30432
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: guardedbox-nginx
    nodePort: 31706
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: guardedbox
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.241.195.29
